<a href="https://colab.research.google.com/github/sriramreddy-7/Brain-Tumor-Prediction/blob/main/Decision_Tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import numpy as np
import matplotlib.pyplot as plt
from skimage.color import rgb2gray
from skimage.transform import resize
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

Importing the required Libraries

In [ ]:
data_dir = '/content/drive/MyDrive/J_CompAIML/DATASET/BTDS'
classes = ['BrainTumor', 'Healthy']
num_classes = len(classes)
img_size = (150,150)


In [ ]:
X = []
y = []
for i, cls in enumerate(classes):
    path = os.path.join(data_dir, cls)
    for img in os.listdir(path):
        try:
            # Convert image to grayscale and resize to a fixed size
            img_array = resize(rgb2gray(plt.imread(os.path.join(path, img))), img_size)
            X.append(img_array)  # Store the image array
            y.append(i)  # Store the class label
        except Exception as e:
            print(e)

the input array must have size 3 along `channel_axis`, got (300, 289)
the input array must have size 3 along `channel_axis`, got (336, 300)
the input array must have size 3 along `channel_axis`, got (1024, 1024)
the input array must have size 3 along `channel_axis`, got (300, 289)
the input array must have size 3 along `channel_axis`, got (360, 319)
the input array must have size 3 along `channel_axis`, got (500, 377)
the input array must have size 3 along `channel_axis`, got (300, 289)
the input array must have size 3 along `channel_axis`, got (1427, 1275)
the input array must have size 3 along `channel_axis`, got (1024, 1024)
the input array must have size 3 along `channel_axis`, got (294, 250)
the input array must have size 3 along `channel_axis`, got (325, 300)
the input array must have size 3 along `channel_axis`, got (360, 319)
the input array must have size 3 along `channel_axis`, got (278, 236)
the input array must have size 3 along `channel_axis`, got (325, 300)
the input arra

In [ ]:
X = np.array(X)
y = np.array(y)

In [ ]:
print(X.shape, y.shape)

(4473, 150, 150) (4473,)


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train = X_train.reshape(X_train.shape[0], -1)
X_test = X_test.reshape(X_test.shape[0], -1)
print(X_test)
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

[[0.07551878 0.07843244 0.08235096 ... 0.07339585 0.07058976 0.07058824]
 [0.00392157 0.00392157 0.00392157 ... 0.00392157 0.00392157 0.00392157]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.09389415 0.10777612 0.12432494 ... 0.14587103 0.07381517 0.46272178]
 [0.07058824 0.07058824 0.07058824 ... 0.07058824 0.07058824 0.07058824]
 [0.         0.         0.         ... 0.         0.         0.        ]]


KeyboardInterrupt: ignored

In [ ]:
print('Accuracy:', acc)
print('Accuracy Percentage:', round(acc*100,3),"%")

Accuracy: 0.8849162011173184
Accuracy Percentage: 88.492 %
